### ISSUE TITLE
add a way to autologin on gnome shell wayland

### ISSUE THREAD

**Issue by davidbepo** [hagabaka/sddm-config-editor#12]
currently new versions of gnome have a wayland session that is selectable from sddm but there is no (obvious) way to autologin on it

**Comment by hagabaka** [comment]
Let me know if the latest commit works.

**Comment by davidbepo** [comment]
it doesnt work,
it adds a second gnome.desktop session but the generated file is the same as the first and it logs on xorg gnome
i think this is due to the gnome wayland session being controlled by an environment variable
note that selecting gnome (wayland) session from sddm works
thanks for the work :)

**Comment by hagabaka** [comment]
I think this is because both the X11 and Wayland GNOME sessions are named gnome.desktop, just in different directories (usually /usr/share/xsessions and /usr/share/wayland-sessions, respetively). When attempting to autologin, SDDM looks in xsessions, and then wayland-sessions, for the configured filename, and uses the first one it finds. So I have two suggestions for you to try:

- Make a copy of /usr/share/wayland-sessions/gnome.desktop, for example /usr/share/wayland-sessions/gnome-wayland.desktop , and set that as the Autologin session.
- Type in the full path of /usr/share/wayland-sessions/gnome.desktop as the Autologin session.

If the second option works, I can probably make sddm-config-editor list the full paths of session files to avoid the problems like yours.

**Comment by davidbepo** [comment]
setting the autologin session to  /usr/share/wayland-sessions/gnome.desktop doesnt work
like i said it needs to be run with XDG_SESSION_TYPE=wayland to work
https://wiki.archlinux.org/index.php/GNOME#Starting_GNOME has more details

**Comment by hagabaka** [comment]
What about making a copy of the wayland gnome.desktop with a unique filename like gnome-wayland.desktop, and setting that in Autologin? SDDM sets XDG_SESSION_TYPE, but I think its code isn't handling this case correctly.

**Comment by davidbepo** [comment]
creating gnome-wayland.desktop and setting it as autologin works!!
